---
- name: Install dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - curl
    - zsh

- name: Clone the repository
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh

- name: Create a new zsh configuration file
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
    backup: true
    remote_src: true

- name: Change default shell
  become: true
  command:
    cmd: chsh -s $(which zsh)
