---
- hosts: localhost
  connection: local
  become: True

  tasks:
    - name: System update
      apt:
        upgrade: yes
        autoremove: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: Install packages
      package:
        name:
          - vim
          - git
          - curl
          - wget
          - htop
          - ranger
          - screen
          - zsh
